version: 2
jobs:
  go1.25: &base
    docker:
      - image: cimg/go:1.25
    steps:
      - run: go version
      - checkout
      - run: go test -race -v -count=100 ./...

  go1.24:
    <<: *base
    docker:
      - image: cimg/go:1.24

  go1.23:
    <<: *base
    docker:
      - image: cimg/go:1.23

  go1.22:
    <<: *base
    docker:
      - image: cimg/go:1.22

workflows:
  version: 2
  build:
    jobs:
      - go1.25
      - go1.24
      - go1.23
      - go1.22
